import * as THREE from 'https://unpkg.com/three@0.185.1/build/three.module.js';

const $ = (s) => document.querySelector(s);
const ASSET = 'assets/textures/';
const files = { grass:'grass_block_top.png', dirt:'dirt.png', stone:'stone.png', wood:'oak_log_side.png', leaves:'leaves.png', water:'water.png' };
const items = Object.keys(files);
const inventory = { grass:2, dirt:0, stone:0, wood:0, leaves:0, water:0 };
let selected='grass', tokens=0, difficulty='easy', question, paused=false, signedOut=false;
const keys=new Set(), dugCells=new Set(); let yaw=0,pitch=0,vy=0,locked=false,last=performance.now(),touchPoint;
const show=(id)=>{ $('#overlay').hidden=false; ['#math-panel','#menu-panel','#signedout-panel'].forEach(x=>$(x).hidden=x!==id); };
const hide=()=>{ $('#overlay').hidden=true; };
const setNotice=(text)=>$('#notice').textContent=text;
function makeQuestion(){ const r=(a,b)=>a+Math.floor(Math.random()*(b-a+1)); if(difficulty==='easy'){let a=r(1,10),b=r(1,10);return{prompt:`${a} + ${b} = ?`,answer:a+b,reward:1};} if(difficulty==='medium'){let a=r(12,99),b=r(12,99);return{prompt:`${a} × ${b} = ?`,answer:a*b,reward:5};} let a=r(2,8),b=r(2,5);return{prompt:`${a}^${b} = ?`,answer:a**b,reward:10}; }
function updateHud(){ $('#tokens').textContent=tokens; $('#selected').textContent=selected; $('#count').textContent=inventory[selected]; $('#difficulty-label').textContent=difficulty.toUpperCase(); $('#hotbar').replaceChildren(...items.filter(x=>inventory[x]>0).map((item,i)=>{const b=document.createElement('button');b.className=item===selected?'chosen':'';b.innerHTML=`<i>${i+1}</i><img src="${ASSET+files[item]}" alt=""><strong>${inventory[item]}</strong>`;b.onclick=()=>{selected=item;updateHud();};return b;})); }
function alter(item,amount){inventory[item]=Math.max(0,inventory[item]+amount);if(!inventory[selected]) selected=items.find(x=>inventory[x]>0)||'grass';updateHud();}
function height(x,z){return Math.max(0,Math.floor(1.2+Math.sin(x*.46)*.7+Math.cos(z*.35)*.55));}
const scene=new THREE.Scene();scene.background=new THREE.Color('#72b8e4');scene.fog=new THREE.Fog('#72b8e4',18,48);const camera=new THREE.PerspectiveCamera(73,innerWidth/innerHeight,.1,120);const renderer=new THREE.WebGLRenderer({antialias:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;$('#scene').append(renderer.domElement);scene.add(new THREE.HemisphereLight('#d8f5ff','#3c623b',2.4));const sun=new THREE.DirectionalLight('#fff2c7',2.1);sun.position.set(18,28,8);scene.add(sun);
const loader=new THREE.TextureLoader(), tex=(file)=>{const t=loader.load(ASSET+file);t.colorSpace=THREE.SRGBColorSpace;t.magFilter=t.minFilter=THREE.NearestFilter;return t;};const maps=Object.fromEntries(Object.entries(files).map(([k,v])=>[k,tex(v)])),side=tex('grass_block_side.png'),geo=new THREE.BoxGeometry(1,1,1),cubes=[];function mat(kind){return kind==='grass'?[new THREE.MeshLambertMaterial({map:side}),new THREE.MeshLambertMaterial({map:side}),new THREE.MeshLambertMaterial({map:maps.grass}),new THREE.MeshLambertMaterial({map:maps.dirt}),new THREE.MeshLambertMaterial({map:side}),new THREE.MeshLambertMaterial({map:side})]:new THREE.MeshLambertMaterial({map:maps[kind],transparent:kind==='water',opacity:kind==='water'?.73:1});}function add(x,y,z,kind){const m=new THREE.Mesh(geo,mat(kind));m.position.set(x,y,z);m.userData.block=kind;scene.add(m);cubes.push(m);return m;}
for(let x=-14;x<=14;x++)for(let z=-14;z<=14;z++){const h=height(x,z);for(let y=-2;y<h;y++)add(x,y,z,y===h-1?'grass':y>h-3?'dirt':'stone');}for(let x=-4;x<=3;x++)for(let z=3;z<=9;z++)add(x,.35,z,'water');[[-9,-7],[-5,-8],[7,-5],[9,4],[-10,5],[4,9]].forEach(([x,z])=>{const h=height(x,z);for(let y=h;y<h+3;y++)add(x,y,z,'wood');for(let dx=-1;dx<=1;dx++)for(let dz=-1;dz<=1;dz++)for(let dy=2;dy<=3;dy++)if(Math.abs(dx)+Math.abs(dz)<3)add(x+dx,h+dy,z+dz,'leaves');});
function surface(x,z){return Math.max(height(x,z),...cubes.filter(c=>c.userData.block!=='water'&&c.position.x===x&&c.position.z===z).map(c=>c.position.y+1));}const player=new THREE.Object3D();player.position.set(0,3,10);player.add(camera);scene.add(player);const ray=new THREE.Raycaster();ray.far=7;const centre=new THREE.Vector2();function jump(){if(player.position.y<=surface(Math.round(player.position.x),Math.round(player.position.z))+1.71)vy=7.3;}
function enter(){if(!paused&&!signedOut)renderer.domElement.requestPointerLock();}renderer.domElement.onclick=enter;renderer.domElement.oncontextmenu=e=>e.preventDefault();document.addEventListener('pointerlockchange',()=>{locked=document.pointerLockElement===renderer.domElement;setNotice(locked?'First-person controller active.':'Click to enter the world.');});document.addEventListener('mousemove',e=>{if(!locked||paused)return;yaw-=e.movementX*.0024;pitch=Math.max(-1.3,Math.min(1.3,pitch-e.movementY*.0024));player.rotation.y=yaw;camera.rotation.x=pitch;});renderer.domElement.addEventListener('mousedown',e=>{if(!locked||paused)return;ray.setFromCamera(centre,camera);const hit=ray.intersectObjects(cubes)[0];if(!hit)return;if(e.button===0){const kind=hit.object.userData.block,p=hit.object.position;if(p.y===height(Math.round(p.x),Math.round(p.z))-1)dugCells.add(`${Math.round(p.x)},${Math.round(p.z)}`);scene.remove(hit.object);cubes.splice(cubes.indexOf(hit.object),1);alter(kind,1);setNotice(`Mined ${kind}. Added to hotbar.`);}else if(e.button===2&&hit.face){if(!inventory[selected])return setNotice(`Mine ${selected} before placing it.`);const p=hit.object.position.clone().add(hit.face.normal);add(Math.round(p.x),Math.round(p.y),Math.round(p.z),selected);alter(selected,-1);}});
window.addEventListener('keydown',e=>{if(e.key==='Escape'){document.exitPointerLock();paused=true;show('#menu-panel');return;}if(e.key.toLowerCase()==='q'){question=makeQuestion();$('#math-title').textContent=`${difficulty.toUpperCase()} KNOWLEDGE CHALLENGE`;$('#question').textContent=question.prompt;$('#reward').textContent=`Correct answer: +${question.reward} tokens`;show('#math-panel');return;}if(e.key===' '){jump();return;}keys.add(e.key.toLowerCase());});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(locked&&!paused){const ox=player.position.x,oz=player.position.z,speed=(keys.has('shift')?8:4.5)*dt,f=new THREE.Vector3(0,0,-1).applyAxisAngle(new THREE.Vector3(0,1,0),yaw),r=new THREE.Vector3(1,0,0).applyAxisAngle(new THREE.Vector3(0,1,0),yaw);if(keys.has('w'))player.position.addScaledVector(f,speed);if(keys.has('s'))player.position.addScaledVector(f,-speed);if(keys.has('a'))player.position.addScaledVector(r,-speed);if(keys.has('d'))player.position.addScaledVector(r,speed);player.position.x=Math.max(-13,Math.min(13,player.position.x));player.position.z=Math.max(-13,Math.min(13,player.position.z));if(dugCells.has(`${Math.round(player.position.x)},${Math.round(player.position.z)}`)){player.position.x=ox;player.position.z=oz;}vy-=18*dt;player.position.y+=vy*dt;const ground=surface(Math.round(player.position.x),Math.round(player.position.z))+1.65;if(player.position.y<ground){player.position.y=ground;vy=0;}}renderer.render(scene,camera);requestAnimationFrame(frame);}requestAnimationFrame(frame);window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
$('#fullscreen').onclick=$('#fullscreen-menu').onclick=()=>document.documentElement.requestFullscreen?.();$('#resume').onclick=()=>{paused=false;hide();enter();};$('#difficulty').onchange=e=>{difficulty=e.target.value;updateHud();};$('#math-menu').onclick=()=>{question=makeQuestion();$('#question').textContent=question.prompt;show('#math-panel');};$('.close').onclick=hide;$('#math-form').onsubmit=e=>{e.preventDefault();if(Number($('#answer').value)===question.answer){tokens+=question.reward;setNotice(`Correct! +${question.reward} tokens.`);}else setNotice(`Answer: ${question.answer}`);$('#answer').value='';updateHud();hide();};function signOut(){document.exitPointerLock();paused=true;signedOut=true;show('#signedout-panel');}$('#signout').onclick=$('#signout-menu').onclick=signOut;$('#restart').onclick=()=>location.reload();
if(matchMedia('(pointer:coarse)').matches){$('#mobile-controls').hidden=false;document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=()=>keys.add(b.dataset.key);b.onpointerup=b.onpointerleave=()=>keys.delete(b.dataset.key);});$('#jump').onpointerdown=jump;const look=$('#look-stick');look.ontouchstart=e=>touchPoint=e.touches[0];look.ontouchmove=e=>{const p=e.touches[0];yaw-=(p.clientX-touchPoint.clientX)*.018;pitch=Math.max(-1.3,Math.min(1.3,pitch-(p.clientY-touchPoint.clientY)*.018));player.rotation.y=yaw;camera.rotation.x=pitch;touchPoint=p;};}question=makeQuestion();updateHud();